/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

// コンパイル時の文字コードをUTF-8に設定
tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

// テスト実行時の文字コードをUTF-8に設定
tasks.withType<Test> {
    systemProperty("file.encoding", "UTF-8")
}

// アプリケーション実行時（gradle run）の文字コードをUTF-8に設定
tasks.withType<JavaExec> {
    systemProperty("file.encoding", "UTF-8")
}